### ISSUE TITLE
“./parser/my-languages.so” 文件缺失

### ISSUE THREAD

**Issue by zlh-source** [Alex-HaochenLi/ReCo#1]
您好，“./parser/my-languages.so”这个文件似乎没有上传到仓库中。

**Comment by Alex-HaochenLi** [comment]
Hello, I have uploaded the `my-languages.so`. Or you could use `sh build.sh` under the `parser` folder to build the parser by yourself.

**Comment by zlh-source** [comment]
Thanks for your response!
