### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by zlh-source** [Alex-HaochenLi/ReCo#2]
In [here](https://github.com/Alex-HaochenLi/ReCo/blob/415c29714dc86c001a7619fbaba03517966dd821/metrics/code_style_sim.py#L278), the "augaug_total" is not defined.

**Comment by Alex-HaochenLi** [comment]
I have fixed it in the new commit. Please have a try :)

**Comment by zlh-source** [comment]
Thanks for your response!
